name: ✨ Feature Request
description: Suggest a new feature or enhancement for Claude Code Builder
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: Describe the problem or limitation you're experiencing.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see added or changed?
      placeholder: Describe your ideal solution in detail.
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - New Pattern
        - Pattern Enhancement
        - Installation/Setup
        - Documentation
        - Testing
        - Claude Code Integration
        - Cross-platform Support
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature in your workflow.
      placeholder: Walk us through a typical scenario where this feature would be helpful.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered? How do they fall short?
      placeholder: Describe any workarounds or alternative solutions you've tried.

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, share them here.
      placeholder: Technical details, code examples, or architectural suggestions.

  - type: input
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      placeholder: e.g., Nice to have, Important for my workflow, Blocking my project

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature aligns with Claude Code Builder's goal of simple, <50-line patterns
          required: true
        - label: I would be willing to help implement or test this feature
          required: false