blank_issues_enabled: false
contact_links:
  - name: 🔒 Security Vulnerability (Private Reporting)
    url: https://github.com/swm-sink/dev-platform/security/advisories/new
    about: Report security vulnerabilities privately using GitHub Security Advisories
  
  - name: 💬 Community Discussions
    url: https://github.com/swm-sink/dev-platform/discussions
    about: Ask questions, share ideas, and connect with the community
  
  - name: 📧 Security Team Contact
    url: mailto:security@dev-platform.org
    about: Direct contact for sensitive security matters
  
  - name: 📚 Claude Code Documentation
    url: https://docs.anthropic.com/en/docs/claude-code
    about: Official Claude Code documentation and guides
  
  - name: 🎓 Dev Platform Learning Hub
    url: https://github.com/swm-sink/dev-platform/wiki
    about: Tutorials, examples, and educational resources (coming soon)